"""Role sources render to Claude Code subagents."""
import pytest
import yaml

from orchi_core import roles

BODY = 'Line with "quotes", a back\\slash, \'\'\' triple, and a\ttab.\n\nRead {{ORCHI_SKILL}}/references/readiness.md.\n'
SKILL = ".claude/skills/orchi"


def source(name="orchi-demo", claude_model="opus", body=BODY):
    model = f'model = "{claude_model}"\n' if claude_model else ""
    return (
        "+++\n"
        f'name = "{name}"\n'
        'description = "Demo: a \\"quoted\\" role."\n\n'
        '[claude]\n'
        f'{model}effort = "low"\ntools = ["Read", "Bash", "Agent"]\n'
        "+++\n\n"
        f"{body}"
    )


def write(directory, text, stem="orchi-demo"):
    path = directory / f"{stem}.md"
    path.write_text(text, encoding="utf-8")
    return path


def test_claude_front_matter(tmp_path):
    role = roles.parse_role(write(tmp_path, source()))
    text = roles.render_claude(role, "/home/user/.claude/skills/orchi")
    lines = text.split("\n")
    assert lines[:7] == [
        "---",
        "name: orchi-demo",
        'description: "Demo: a \\"quoted\\" role."',
        "tools: Read, Bash, Agent",
        "model: opus",
        "effort: low",
        "---",
    ]
    assert lines[7] == "<!-- Generated by Orchi from .claude/skills/orchi/roles/orchi-demo.md; reinstall to update, do not edit. -->"
    assert text.endswith("\n\n" + BODY.replace("{{ORCHI_SKILL}}", "/home/user/.claude/skills/orchi"))
    assert yaml.safe_load(text.split("---", 2)[1])["description"] == 'Demo: a "quoted" role.'


def test_del_in_description_is_escaped_yaml(tmp_path):
    role = roles.parse_role(write(tmp_path, source().replace('role."', 'role.\\u007f"')))
    text = roles.render_claude(role, SKILL)
    assert "\x7f" not in text
    assert yaml.safe_load(text.split("---", 2)[1])["description"] == 'Demo: a "quoted" role.\x7f'


@pytest.mark.parametrize("text, match", [
    (source(claude_model=None), r"\[claude.model\]"),
    (source().replace('model = "opus"', 'model = "opus # x"'), r"\[claude.model\]"),
    (source().replace('effort = "low"', 'effort = "low: high"'), r"\[claude.effort\]"),
    (source(name="orchi-other"), "must match the file stem"),
    (source(body="Use {{OTHER}} here.\n"), "unknown placeholder"),
    (source(body="\n"), "body is empty"),
    (source().replace("+++\n\n", "\n", 1), "not closed"),
    ("name = 'x'\n", 'must start with a "\\+\\+\\+"'),
])
def test_invalid_role_rejected(tmp_path, text, match):
    with pytest.raises(roles.RoleError, match=match):
        roles.parse_role(write(tmp_path, text))


def test_load_reports_every_invalid_role_and_ignores_readme(tmp_path):
    write(tmp_path, source())
    write(tmp_path, source(name="orchi-bad", claude_model=None), stem="orchi-bad")
    (tmp_path / "README.md").write_text("# Roles\n")
    with pytest.raises(roles.RoleError, match="orchi-bad.md"):
        roles.load_roles(tmp_path)
    (tmp_path / "orchi-bad.md").unlink()
    assert [role.name for role in roles.load_roles(tmp_path)] == ["orchi-demo"]


def test_agent_files_render_every_role(tmp_path):
    write(tmp_path, source())
    files = roles.agent_files(SKILL, tmp_path)
    assert list(files) == [".claude/agents/orchi-demo.md"]
    assert files[".claude/agents/orchi-demo.md"].decode() == roles.render_claude(roles.load_roles(tmp_path)[0], SKILL)


def test_shipped_roles_have_agreed_models_and_nesting():
    expected = {
        "orchi-scout": ("haiku", "medium", ["Read", "Grep", "Glob", "Bash", "Agent"]),
        "orchi-implementer": ("opus", "low", ["Read", "Edit", "Write", "Grep", "Glob", "Bash", "Agent"]),
        "orchi-fixer": ("sonnet", "medium", ["Read", "Edit", "Write", "Grep", "Glob", "Bash", "Agent"]),
        "orchi-reviewer": ("opus", "high", ["Read", "Grep", "Glob", "Bash", "Agent"]),
    }
    loaded = {role.name: role for role in roles.load_roles()}
    assert sorted(loaded) == sorted(expected)
    for name, (model, effort, tools) in expected.items():
        role = loaded[name]
        claude = role.meta["claude"]
        assert (claude["model"], claude["effort"]) == (model, effort)
        assert set(role.meta) == {"name", "description", "claude"}
        assert claude["tools"] == tools
        assert "## Nested agents" in role.body
        # Compare prose with whitespace collapsed so rewrapping the role text does not fail the check.
        prose = " ".join(role.body.split())
        assert "The main session alone starts `orchi-implementer` and `orchi-fixer`." in prose
        assert "Only `orchi-implementer` and `orchi-fixer` edit files or commit." in prose
        assert "spawn" not in role.body.lower()
        # Project-neutral: installed roles reach Orchi files only through the placeholder.
        assert ".github/AGENTS.md" not in role.body and "skills/orchi/" not in role.body.replace("{{ORCHI_SKILL}}", "")
