"""Role sources render to Claude Code and Codex subagents."""
import tomllib

import pytest
import yaml

from orchi_core import roles

BODY = 'Line with "quotes", a back\\slash, \'\'\' triple, and a\ttab.\n\nRead {{ORCHI_SKILL}}/references/readiness.md.\n'
SKILL = ".agents/skills/orchi"


def source(name="orchi-demo", codex_model="gpt-6-sol", body=BODY):
    model = f'model = "{codex_model}"\n' if codex_model else ""
    return (
        "+++\n"
        f'name = "{name}"\n'
        'description = "Demo: a \\"quoted\\" role."\n\n'
        '[claude]\nmodel = "opus"\neffort = "low"\ntools = ["Read", "Bash", "Agent"]\n\n'
        f'[codex]\n{model}model_reasoning_effort = "low"\n'
        "+++\n\n"
        f"{body}"
    )


def write(directory, text, stem="orchi-demo"):
    path = directory / f"{stem}.md"
    path.write_text(text, encoding="utf-8")
    return path


def test_codex_toml_round_trips_body_with_substituted_skill(tmp_path):
    role = roles.parse_role(write(tmp_path, source()))
    data = tomllib.loads(roles.render_codex(role, SKILL))
    assert data["developer_instructions"] == BODY.replace("{{ORCHI_SKILL}}", SKILL)
    assert data["name"] == "orchi-demo"
    assert data["description"] == 'Demo: a "quoted" role.'
    assert (data["model"], data["model_reasoning_effort"]) == ("gpt-6-sol", "low")
    assert roles.render_codex(role, SKILL).startswith(
        "# Generated by Orchi from .agents/skills/orchi/roles/orchi-demo.md; reinstall to update, do not edit.\n")


def test_literal_string_used_when_safe():
    body = 'Plain "body" with a back\\slash.\n'
    assert roles.toml_multiline(body).startswith("'''")
    assert tomllib.loads("x = " + roles.toml_multiline(body))["x"] == body


def test_claude_front_matter(tmp_path):
    role = roles.parse_role(write(tmp_path, source()))
    text = roles.render_claude(role, "/home/user/.agents/skills/orchi")
    lines = text.split("\n")
    assert lines[:7] == [
        "---",
        "name: orchi-demo",
        'description: "Demo: a \\"quoted\\" role."',
        "tools: Read, Bash, Agent",
        "model: opus",
        "effort: low",
        "---",
    ]
    assert lines[7] == "<!-- Generated by Orchi from .agents/skills/orchi/roles/orchi-demo.md; reinstall to update, do not edit. -->"
    assert text.endswith("\n\n" + BODY.replace("{{ORCHI_SKILL}}", "/home/user/.agents/skills/orchi"))
    assert yaml.safe_load(text.split("---", 2)[1])["description"] == 'Demo: a "quoted" role.'


def test_del_in_description_is_valid_toml(tmp_path):
    role = roles.parse_role(write(tmp_path, source().replace('role."', 'role.\\u007f"')))
    assert tomllib.loads(roles.render_codex(role, SKILL))["description"] == 'Demo: a "quoted" role.\x7f'


def test_control_characters_in_body_round_trip(tmp_path):
    body = "Bell \x07 and delete \x7f with ''' quotes.\n"
    role = roles.parse_role(write(tmp_path, source(body=body)))
    assert tomllib.loads(roles.render_codex(role, SKILL))["developer_instructions"] == body


@pytest.mark.parametrize("text, match", [
    (source(codex_model=None), r"\[codex.model\]"),
    (source().replace('model = "opus"', 'model = "opus # x"'), r"\[claude.model\]"),
    (source().replace('effort = "low"', 'effort = "low: high"'), r"\[claude.effort\]"),
    (source(name="orchi-other"), "must match the file stem"),
    (source(body="Use {{OTHER}} here.\n"), "unknown placeholder"),
    (source(body="\n"), "body is empty"),
    (source().replace("+++\n\n", "\n", 1), "not closed"),
    ("name = 'x'\n", 'must start with a "\\+\\+\\+"'),
])
def test_invalid_role_rejected(tmp_path, text, match):
    with pytest.raises(roles.RoleError, match=match):
        roles.parse_role(write(tmp_path, text))


def test_load_reports_every_invalid_role_and_ignores_readme(tmp_path):
    write(tmp_path, source())
    write(tmp_path, source(name="orchi-bad", codex_model=None), stem="orchi-bad")
    (tmp_path / "README.md").write_text("# Roles\n")
    with pytest.raises(roles.RoleError, match="orchi-bad.md"):
        roles.load_roles(tmp_path)
    (tmp_path / "orchi-bad.md").unlink()
    assert [role.name for role in roles.load_roles(tmp_path)] == ["orchi-demo"]


def test_agent_files_follow_selected_hosts(tmp_path):
    write(tmp_path, source())
    assert list(roles.agent_files(["copilot"], SKILL, tmp_path)) == []
    assert list(roles.agent_files(["claude"], SKILL, tmp_path)) == [".claude/agents/orchi-demo.md"]
    assert list(roles.agent_files(["codex", "claude"], SKILL, tmp_path)) == [
        ".claude/agents/orchi-demo.md", ".codex/agents/orchi-demo.toml"]


def test_shipped_roles_have_agreed_models_and_nesting():
    expected = {
        "orchi-scout": ("haiku", "medium", "gpt-6-luna", "medium", ["Read", "Grep", "Glob", "Bash", "Agent"]),
        "orchi-implementer": ("opus", "low", "gpt-6-sol", "low", ["Read", "Edit", "Write", "Grep", "Glob", "Bash", "Agent"]),
        "orchi-fixer": ("sonnet", "medium", "gpt-6-luna", "high", ["Read", "Edit", "Write", "Grep", "Glob", "Bash", "Agent"]),
        "orchi-reviewer": ("opus", "high", "gpt-6-sol", "medium", ["Read", "Grep", "Glob", "Bash", "Agent"]),
    }
    loaded = {role.name: role for role in roles.load_roles()}
    assert sorted(loaded) == sorted(expected)
    for name, (claude_model, effort, codex_model, codex_effort, tools) in expected.items():
        role = loaded[name]
        claude, codex = role.meta["claude"], role.meta["codex"]
        assert (claude["model"], claude["effort"], codex["model"], codex["model_reasoning_effort"]) == (
            claude_model, effort, codex_model, codex_effort)
        assert claude["tools"] == tools
        assert "## Nested agents" in role.body
        assert "The main session alone starts\n  `orchi-implementer` and `orchi-fixer`." in role.body
        assert "Only `orchi-implementer` and `orchi-fixer` edit files or commit." in role.body
        assert "spawn" not in role.body.lower()
        # Project-neutral: installed roles reach Orchi files only through the placeholder.
        assert ".github/AGENTS.md" not in role.body and ".agents/skills/orchi" not in role.body
